Feature/domain entities
ines-mgg/Triumph-Motorcycles pull request #6
Opened 2024-10-28 10:11 UTC by justinDev91

## What type of PR is this? (check all applicable)

- [X] :pizza: Feature
- [ ] :bug: Bug(s) fix
- [ ] :pencil: Wiki update
- [ ] :lipstick: Style
- [ ] :fire: Performance improvements
- [ ] :white_check_mark: Tests (unit and/or E2E)
- [ ] :repeat: CI/CD
- [ ] :fast_forward: Revert

## Description
Implémentation des entités dans domain/entities

## Related Tickets & Documents

- Related Issue #
- Closes #

## UI accessibility checklist

_If your PR includes UI changes, please utilize this checklist:_

- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested with [webAIM](https://webaim.org/resources/contrastchecker/) ?

## Added/updated tests?

- [ ] :+1: Yes
- [ ] :no*good: No, and this is why: \_please replace this line with details on why tests
      have not been included*
- [ ] :raising_hand: I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

2024-11-01 18:41 UTC, ines-mgg requested changes
Don't use french for tests files (I made an example with driver.test.ts, don't forget to pull to see the fix). Also, I prefer using "it" instead of "test" with jest but it's ok.
Overall it's great, but I don't know how to fix the issue with maintenance.test.ts

2024-11-04 10:58 UTC, justinDev91 commented
Je vais update tous les tests en anglais. Quel e issue with maintenance.test.ts @ines-mgg ?

2024-11-04 11:05 UTC, ines-mgg commented
> Je vais update tous les tests en anglais. Quel e issue with maintenance.test.ts @ines-mgg ?

![image](https://github.com/user-attachments/assets/efe4480b-b722-4574-9ddc-aed385b228e7)

2024-11-04 11:22 UTC, justinDev91 commented
Bizarrement, j'ai pas ce problème chez moi: 
<img width="484" alt="image" src="https://github.com/user-attachments/assets/eadd40b0-bfb6-4ee7-97b6-976c0c69b98e">

2024-11-04 11:23 UTC, ines-mgg commented
Alors là je sais pas pourquoi ça bug sur la pipeline :/

2024-11-04 13:17 UTC, justinDev91 commented
Je m'en occupe. Si j'y arrive pas alors je supprimerai cette ligne de test. @ines-mgg

2025-01-22 19:28 UTC, closed without merging